# Generated by Django 5.2.9 on 2025-12-06 17:57

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertiseIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(default='Nos Expertises', max_length=255, verbose_name='Titre principal')),
                ('hero_subtitle', models.CharField(blank=True, max_length=500, verbose_name='Sous-titre')),
                ('introduction', wagtail.fields.RichTextField(blank=True, verbose_name='Introduction')),
            ],
            options={
                'verbose_name': 'Page Index des Expertises',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ExpertisePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('icon', models.CharField(blank=True, help_text="Nom de l'icône (ex: 'code', 'design', 'analytics')", max_length=50, verbose_name='Icône')),
                ('summary', models.TextField(blank=True, max_length=500, verbose_name='Résumé')),
                ('description', wagtail.fields.RichTextField(blank=True, verbose_name='Description détaillée')),
                ('key_points', wagtail.fields.RichTextField(blank=True, help_text='Liste des points clés de cette expertise', verbose_name='Points clés')),
                ('technologies', models.CharField(blank=True, help_text='Séparées par des virgules', max_length=500, verbose_name='Technologies utilisées')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=255)),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image principale')),
            ],
            options={
                'verbose_name': 'Page Expertise',
            },
            bases=('wagtailcore.page',),
        ),
    ]
