# Generated by Django 5.2.9 on 2025-12-07 11:12

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertise', '0002_expertiseindexpage_hero_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertisepage',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='expertisepage',
            name='key_points',
        ),
        migrations.RemoveField(
            model_name='expertisepage',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='expertisepage',
            name='technologies',
        ),
        migrations.AddField(
            model_name='expertisepage',
            name='body',
            field=wagtail.fields.StreamField([('section', 0), ('image', 1), ('list', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Point'}), 3: ('wagtail.blocks.ListBlock', (2,), {})}),
        ),
        migrations.AddField(
            model_name='expertisepage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
