# Generated by Django 5.2.9 on 2025-12-10 10:54

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expertise', '0003_remove_expertisepage_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertisepage',
            name='body',
        ),
        migrations.AddField(
            model_name='expertisepage',
            name='faq',
            field=wagtail.fields.StreamField([('faq', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'label': 'Question'}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Réponse'}), 2: ('wagtail.blocks.StructBlock', [[('question', 0), ('answer', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {})}),
        ),
    ]
