# Generated by Django 5.2.9 on 2025-12-10 11:17

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expertise', '0004_remove_expertisepage_body_expertisepage_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertisepage',
            name='faq',
            field=wagtail.fields.StreamField([('items', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'label': 'Question'}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Réponse'}), 2: ('wagtail.blocks.StructBlock', [[('question', 0), ('answer', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {})}),
        ),
    ]
