# Generated by Django 5.2.9 on 2025-12-06 17:57

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(default='Rejoignez Notre Équipe', max_length=255, verbose_name='Titre principal')),
                ('hero_subtitle', models.CharField(blank=True, max_length=500, verbose_name='Sous-titre')),
                ('introduction', wagtail.fields.RichTextField(blank=True, verbose_name='Introduction')),
                ('why_join_title', models.CharField(default='Pourquoi nous rejoindre ?', max_length=255, verbose_name="Titre 'Pourquoi nous rejoindre'")),
                ('why_join_content', wagtail.fields.RichTextField(blank=True, verbose_name="Contenu 'Pourquoi nous rejoindre'")),
                ('culture_title', models.CharField(default='Notre Culture', max_length=255, verbose_name='Titre de la culture')),
                ('culture_content', wagtail.fields.RichTextField(blank=True, verbose_name='Contenu de la culture')),
                ('benefits_title', models.CharField(default='Avantages', max_length=255, verbose_name='Titre des avantages')),
                ('benefits_content', wagtail.fields.RichTextField(blank=True, verbose_name='Contenu des avantages')),
                ('open_positions_title', models.CharField(default='Postes Ouverts', max_length=255, verbose_name='Titre des postes ouverts')),
                ('open_positions_content', wagtail.fields.RichTextField(blank=True, help_text='Listez les postes actuellement ouverts', verbose_name='Contenu des postes ouverts')),
                ('application_email', models.EmailField(blank=True, help_text='Email pour recevoir les candidatures', max_length=254, verbose_name='Email de candidature')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name="Image d'en-tête")),
            ],
            options={
                'verbose_name': 'Page Recrutement',
            },
            bases=('wagtailcore.page',),
        ),
    ]
