# Generated by Django 5.2.9 on 2025-12-07 15:59

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True)),
                ('culture', wagtail.fields.StreamField([('element', 2)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'label': 'Texte'}), 1: ('wagtail.blocks.URLBlock', (), {'label': 'Vidéo (YouTube/Vimeo)', 'required': False}), 2: ('wagtail.blocks.StreamBlock', [[('text', 0), ('video', 1)]], {})})),
                ('testimonials', wagtail.fields.StreamField([('testimonial', 3)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {'label': 'Citation'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Nom'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Poste'}), 3: ('wagtail.blocks.StructBlock', [[('quote', 0), ('name', 1), ('role', 2)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
