# Generated by Django 5.2.9 on 2025-12-08 10:13

import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.forms.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_recruitmentindexpage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Type de contrat')),
            ],
        ),
        migrations.RemoveField(
            model_name='recruitmentpage',
            name='application_email',
        ),
        migrations.RemoveField(
            model_name='recruitmentpage',
            name='benefits_content',
        ),
        migrations.RemoveField(
            model_name='recruitmentpage',
            name='benefits_title',
        ),
        migrations.RemoveField(
            model_name='recruitmentpage',
            name='culture_content',
        ),
        migrations.RemoveField(
            model_name='recruitmentpage',
            name='culture_title',
        ),
        migrations.RemoveField(
            model_name='recruitmentpage',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='recruitmentpage',
            name='hero_subtitle',
        ),
        migrations.RemoveField(
            model_name='recruitmentpage',
            name='hero_title',
        ),
        migrations.RemoveField(
            model_name='recruitmentpage',
            name='open_positions_content',
        ),
        migrations.RemoveField(
            model_name='recruitmentpage',
            name='open_positions_title',
        ),
        migrations.RemoveField(
            model_name='recruitmentpage',
            name='why_join_content',
        ),
        migrations.RemoveField(
            model_name='recruitmentpage',
            name='why_join_title',
        ),
        migrations.AddField(
            model_name='recruitmentindexpage',
            name='from_address',
            field=models.EmailField(blank=True, max_length=255, verbose_name='from address'),
        ),
        migrations.AddField(
            model_name='recruitmentindexpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name="Image d'en-tête"),
        ),
        migrations.AddField(
            model_name='recruitmentindexpage',
            name='hero_title',
            field=models.CharField(default='Rejoignez Notre Équipe', max_length=255, verbose_name='Titre principal'),
        ),
        migrations.AddField(
            model_name='recruitmentindexpage',
            name='subject',
            field=models.CharField(blank=True, max_length=255, verbose_name='subject'),
        ),
        migrations.AddField(
            model_name='recruitmentindexpage',
            name='to_address',
            field=models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, validators=[wagtail.contrib.forms.models.validate_to_address], verbose_name='to address'),
        ),
        migrations.AddField(
            model_name='recruitmentpage',
            name='description',
            field=wagtail.fields.StreamField([('content', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.ListBlock', (1,), {'label': 'Liste'}), 3: ('wagtail.blocks.StreamBlock', [[('text', 0), ('list', 2)]], {})}),
        ),
        migrations.AddField(
            model_name='recruitmentpage',
            name='job_title',
            field=models.CharField(default=1, max_length=255, verbose_name='Poste'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recruitmentpage',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Localisation'),
        ),
        migrations.AlterField(
            model_name='recruitmentindexpage',
            name='culture',
            field=wagtail.fields.StreamField([('element', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'label': 'Texte'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'label': 'Vidéo (YouTube/Vimeo)', 'required': False}), 3: ('wagtail.blocks.StreamBlock', [[('text', 0), ('image', 1), ('video', 2)]], {})}, verbose_name='Ambiance / Culture interne'),
        ),
        migrations.AlterField(
            model_name='recruitmentindexpage',
            name='testimonials',
            field=wagtail.fields.StreamField([('testimonial', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Nom'}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Citation'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Poste'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Photo', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('name', 0), ('quote', 1), ('role', 2), ('photo', 3)]], {})}, verbose_name='Témoignages collaborateurs'),
        ),
        migrations.AddField(
            model_name='recruitmentpage',
            name='contract_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_pages', to='recruitment.contracttype', verbose_name='Type de contrat'),
        ),
        migrations.CreateModel(
            name='JobApplicationFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.TextField(blank=True, help_text='Default value. Comma or new line separated values supported for checkboxes.', verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='recruitment.recruitmentindexpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
