# Generated by Django 5.2.9 on 2025-12-08 10:32

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_contracttype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracttype',
            name='page',
            field=modelcluster.fields.ParentalKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contract_types', to='recruitment.recruitmentindexpage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contracttype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Type de contrat'),
        ),
        migrations.AlterField(
            model_name='recruitmentindexpage',
            name='testimonials',
            field=wagtail.fields.StreamField([('testimonial', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Nom'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Poste'}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Citation'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Photo', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('name', 0), ('role', 1), ('quote', 2), ('photo', 3)]], {})}, verbose_name='Témoignages collaborateurs'),
        ),
    ]
