# Generated by Django 5.2.9 on 2025-12-08 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_recruitmentformsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentformsubmission',
            name='job_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_submissions', to='recruitment.recruitmentpage', verbose_name='Poste concerné'),
        ),
    ]
