# Generated by Django 5.2.9 on 2025-12-10 13:13

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_jobapplicationsubmission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentindexpage',
            name='culture',
            field=wagtail.fields.StreamField([('element', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'label': 'Texte'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'label': 'Vidéo (YouTube/Vimeo)', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('text', 0), ('image', 1), ('video', 2)]], {})}, verbose_name='Ambiance / Culture interne'),
        ),
    ]
