# Generated by Django 5.2.9 on 2025-12-10 13:35

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_alter_recruitmentindexpage_culture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitmentpage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='recruitmentpage',
            name='introduction',
        ),
        migrations.AddField(
            model_name='recruitmentpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='recruitmentpage',
            name='salary',
            field=models.CharField(blank=True, max_length=255, verbose_name='Salaire'),
        ),
    ]
