# Generated by Django 5.2.9 on 2025-12-04 13:55

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(default='Mentions Légales & RGPD', max_length=255, verbose_name='Titre principal')),
                ('introduction', wagtail.fields.RichTextField(blank=True, verbose_name='Introduction')),
                ('legal_title', models.CharField(default='Mentions Légales', max_length=255, verbose_name='Titre des mentions légales')),
                ('legal_content', wagtail.fields.RichTextField(blank=True, help_text="Informations légales sur l'entreprise, l'éditeur du site, etc.", verbose_name='Contenu des mentions légales')),
                ('privacy_title', models.CharField(default='Politique de Confidentialité', max_length=255, verbose_name='Titre de la politique de confidentialité')),
                ('privacy_content', wagtail.fields.RichTextField(blank=True, verbose_name='Contenu de la politique de confidentialité')),
                ('gdpr_title', models.CharField(default='Protection des Données (RGPD)', max_length=255, verbose_name='Titre RGPD')),
                ('gdpr_content', wagtail.fields.RichTextField(blank=True, help_text='Informations sur la protection des données personnelles', verbose_name='Contenu RGPD')),
                ('cookies_title', models.CharField(default='Politique des Cookies', max_length=255, verbose_name='Titre de la politique des cookies')),
                ('cookies_content', wagtail.fields.RichTextField(blank=True, verbose_name='Contenu de la politique des cookies')),
                ('terms_title', models.CharField(default="Conditions d'Utilisation", max_length=255, verbose_name="Titre des conditions d'utilisation")),
                ('terms_content', wagtail.fields.RichTextField(blank=True, verbose_name="Contenu des conditions d'utilisation")),
                ('last_updated', models.DateField(blank=True, null=True, verbose_name='Dernière mise à jour')),
            ],
            options={
                'verbose_name': 'Page Légale',
            },
            bases=('wagtailcore.page',),
        ),
    ]
