# Generated by Django 5.2.9 on 2025-12-08 15:34

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legalpage',
            name='cookies_content',
        ),
        migrations.RemoveField(
            model_name='legalpage',
            name='cookies_title',
        ),
        migrations.RemoveField(
            model_name='legalpage',
            name='gdpr_content',
        ),
        migrations.RemoveField(
            model_name='legalpage',
            name='gdpr_title',
        ),
        migrations.RemoveField(
            model_name='legalpage',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='legalpage',
            name='legal_content',
        ),
        migrations.RemoveField(
            model_name='legalpage',
            name='legal_title',
        ),
        migrations.RemoveField(
            model_name='legalpage',
            name='privacy_content',
        ),
        migrations.RemoveField(
            model_name='legalpage',
            name='privacy_title',
        ),
        migrations.RemoveField(
            model_name='legalpage',
            name='terms_content',
        ),
        migrations.RemoveField(
            model_name='legalpage',
            name='terms_title',
        ),
        migrations.AddField(
            model_name='legalpage',
            name='cookies_policy',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Politique de cookies'),
        ),
        migrations.AddField(
            model_name='legalpage',
            name='legal_notice',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Mentions légales'),
        ),
        migrations.AddField(
            model_name='legalpage',
            name='privacy_policy',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Politique de confidentialité'),
        ),
        migrations.AddField(
            model_name='legalpage',
            name='rgpd_rights',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Droits RGPD'),
        ),
    ]
