# Generated by Django 5.2.9 on 2025-12-10 13:31

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blogpage_categories_remove_blogpage_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='body',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='content',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Contenu'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='reading_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temps de lecture'),
        ),
    ]
