# Generated by Django 5.2.9 on 2025-12-04 13:55

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(default='Bienvenue', max_length=255, verbose_name='Titre principal')),
                ('hero_subtitle', models.CharField(blank=True, max_length=500, verbose_name='Sous-titre')),
                ('hero_cta_text', models.CharField(default='En savoir plus', max_length=50, verbose_name='Texte du bouton CTA')),
                ('hero_cta_link', models.CharField(blank=True, help_text='URL relative (ex: /expertise/) ou absolue', max_length=255, verbose_name='Lien du bouton CTA')),
                ('introduction', wagtail.fields.RichTextField(blank=True, verbose_name='Introduction')),
                ('services_title', models.CharField(default='Nos Services', max_length=255, verbose_name='Titre de la section services')),
                ('services_description', wagtail.fields.RichTextField(blank=True, verbose_name='Description des services')),
                ('stats_title', models.CharField(default='Nos Chiffres', max_length=255, verbose_name='Titre de la section statistiques')),
                ('stat1_number', models.CharField(blank=True, max_length=50, verbose_name='Statistique 1 - Nombre')),
                ('stat1_label', models.CharField(blank=True, max_length=100, verbose_name='Statistique 1 - Label')),
                ('stat2_number', models.CharField(blank=True, max_length=50, verbose_name='Statistique 2 - Nombre')),
                ('stat2_label', models.CharField(blank=True, max_length=100, verbose_name='Statistique 2 - Label')),
                ('stat3_number', models.CharField(blank=True, max_length=50, verbose_name='Statistique 3 - Nombre')),
                ('stat3_label', models.CharField(blank=True, max_length=100, verbose_name='Statistique 3 - Label')),
                ('stat4_number', models.CharField(blank=True, max_length=50, verbose_name='Statistique 4 - Nombre')),
                ('stat4_label', models.CharField(blank=True, max_length=100, verbose_name='Statistique 4 - Label')),
                ('cta_title', models.CharField(default='Prêt à démarrer votre projet ?', max_length=255, verbose_name='Titre CTA final')),
                ('cta_description', models.TextField(blank=True, verbose_name='Description CTA final')),
                ('cta_button_text', models.CharField(default='Contactez-nous', max_length=50, verbose_name='Texte du bouton CTA final')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name="Image d'en-tête")),
            ],
            options={
                'verbose_name': "Page d'Accueil",
            },
            bases=('wagtailcore.page',),
        ),
    ]
