# Generated by Django 5.2.9 on 2025-12-07 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='cta_description',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='cta_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_cta_link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='services_description',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='services_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='stats_title',
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_linked_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Lien du bouton CTA'),
        ),
    ]
