# Generated by Django 5.2.9 on 2025-12-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_button_linked_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='video',
            field=models.URLField(blank=True, verbose_name='Vidéo (YouTube/Vimeo)'),
        ),
    ]
