# Generated by Django 5.2.9 on 2025-12-06 17:57

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(default='Qui sommes-nous ?', max_length=255, verbose_name='Titre principal')),
                ('hero_subtitle', models.CharField(blank=True, max_length=500, verbose_name='Sous-titre')),
                ('introduction', wagtail.fields.RichTextField(blank=True, verbose_name='Introduction')),
                ('mission_title', models.CharField(default='Notre Mission', max_length=255, verbose_name='Titre de la mission')),
                ('mission_content', wagtail.fields.RichTextField(blank=True, verbose_name='Contenu de la mission')),
                ('vision_title', models.CharField(default='Notre Vision', max_length=255, verbose_name='Titre de la vision')),
                ('vision_content', wagtail.fields.RichTextField(blank=True, verbose_name='Contenu de la vision')),
                ('values_title', models.CharField(default='Nos Valeurs', max_length=255, verbose_name='Titre des valeurs')),
                ('values_content', wagtail.fields.RichTextField(blank=True, verbose_name='Contenu des valeurs')),
                ('team_title', models.CharField(default='Notre Équipe', max_length=255, verbose_name="Titre de l'équipe")),
                ('team_description', wagtail.fields.RichTextField(blank=True, verbose_name="Description de l'équipe")),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name="Image d'en-tête")),
            ],
            options={
                'verbose_name': 'Page À Propos',
            },
            bases=('wagtailcore.page',),
        ),
    ]
