# Generated by Django 5.2.9 on 2025-12-07 09:38

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='team_description',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='team_title',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='content',
            field=wagtail.fields.StreamField([('timeline', 3), ('key_numbers', 7), ('leadership', 13)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'année', 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'form_classname': 'événement', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('year', 0), ('event', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {}), 4: ('wagtail.blocks.CharBlock', (), {'form_classname': 'nombre', 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'form_classname': 'label', 'required': True}), 6: ('wagtail.blocks.StructBlock', [[('number', 4), ('label', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'form_classname': 'photo', 'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'form_classname': 'nom', 'required': True}), 10: ('wagtail.blocks.CharBlock', (), {'form_classname': 'position', 'required': True}), 11: ('wagtail.blocks.TextBlock', (), {'form_classname': 'bio', 'required': True}), 12: ('wagtail.blocks.StructBlock', [[('photo', 8), ('name', 9), ('position', 10), ('bio', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {})}),
        ),
    ]
