# Generated by Django 5.2.9 on 2025-12-07 10:18

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_remove_aboutpage_team_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='content',
            field=wagtail.fields.StreamField([('timeline', 3), ('key_numbers', 7), ('leadership', 13)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'année', 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'événement', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('year', 0), ('event', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {'label': 'histoire'}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'nombre', 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'label', 'required': True}), 6: ('wagtail.blocks.StructBlock', [[('number', 4), ('label', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'label': 'chiffres clés'}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'photo', 'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'nom', 'required': True}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'position', 'required': True}), 11: ('wagtail.blocks.TextBlock', (), {'label': 'bio', 'required': True}), 12: ('wagtail.blocks.StructBlock', [[('photo', 8), ('name', 9), ('position', 10), ('bio', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'label': 'équipe dirigeante'})}),
        ),
    ]
