# Generated by Django 5.2.9 on 2025-12-10 11:17

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_aboutpage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='content',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='key_numbers',
            field=wagtail.fields.StreamField([('numbers', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'nombre', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'label', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('number', 0), ('label', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {})}),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='leadership',
            field=wagtail.fields.StreamField([('members', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'photo', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'nom', 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'position', 'required': True}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'bio', 'required': True}), 4: ('wagtail.blocks.StructBlock', [[('photo', 0), ('name', 1), ('position', 2), ('bio', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {})}),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='timeline',
            field=wagtail.fields.StreamField([('items', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'année', 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'événement', 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'description', 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('year', 0), ('event', 1), ('description', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {})}),
        ),
    ]
