# Generated by Django 5.2.9 on 2025-12-10 11:43

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_remove_aboutpage_content_aboutpage_key_numbers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='key_numbers',
            field=wagtail.fields.StreamField([('numbers', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'chiffre', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'label', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('number', 0), ('label', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {})}),
        ),
    ]
