# Generated by Django 5.2.9 on 2025-12-06 17:57

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(default='Nos Réalisations', max_length=255, verbose_name='Titre principal')),
                ('hero_subtitle', models.CharField(blank=True, max_length=500, verbose_name='Sous-titre')),
                ('introduction', wagtail.fields.RichTextField(blank=True, verbose_name='Introduction')),
                ('clients_title', models.CharField(default='Nos Clients', max_length=255, verbose_name='Titre de la section clients')),
            ],
            options={
                'verbose_name': 'Page Index du Portfolio',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ClientLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('client_name', models.CharField(max_length=255, verbose_name='Nom du client')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_logos', to='portfolio.portfolioindexpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PortfolioPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('client_name', models.CharField(blank=True, max_length=255, verbose_name='Nom du client')),
                ('project_date', models.DateField(blank=True, null=True, verbose_name='Date du projet')),
                ('summary', models.TextField(blank=True, max_length=500, verbose_name='Résumé')),
                ('challenge', wagtail.fields.RichTextField(blank=True, verbose_name='Défi / Problématique')),
                ('solution', wagtail.fields.RichTextField(blank=True, verbose_name='Solution apportée')),
                ('results', wagtail.fields.RichTextField(blank=True, verbose_name='Résultats')),
                ('technologies', models.CharField(blank=True, help_text='Séparées par des virgules', max_length=500, verbose_name='Technologies utilisées')),
                ('project_url', models.URLField(blank=True, verbose_name='URL du projet')),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image principale')),
            ],
            options={
                'verbose_name': 'Page Projet',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PortfolioGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Légende')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image', verbose_name='Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='portfolio.portfoliopage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
