# Generated by Django 5.2.9 on 2025-12-07 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientLogo',
        ),
    ]
