# Generated by Django 5.2.9 on 2025-12-07 13:00

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_clientopinion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientopinion',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_opinion', to='portfolio.portfolioindexpage'),
        ),
    ]
