# Generated by Django 5.2.9 on 2025-12-07 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_clientopinion_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortfolioGalleryImage',
        ),
    ]
