# Generated by Django 5.2.9 on 2025-12-07 13:13

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_delete_portfoliogalleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientopinion',
            name='author',
            field=models.CharField(blank=True, verbose_name='auteur'),
        ),
        migrations.AddField(
            model_name='clientopinion',
            name='quote',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='avis de client'),
        ),
    ]
