# Generated by Django 5.2.9 on 2025-12-07 13:33

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_clientopinion_author_clientopinion_quote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliopage',
            options={'verbose_name': "Page cas d'étude"},
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='body',
            field=wagtail.fields.StreamField([('text', 0), ('image', 1), ('list', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {}), 3: ('wagtail.blocks.ListBlock', (2,), {})}),
        ),
    ]
