# Generated by Django 5.2.9 on 2025-12-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_portfoliopage_options_portfoliopage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientopinion',
            name='author',
            field=models.CharField(blank=True, verbose_name='Poste'),
        ),
    ]
