# Generated by Django 5.2.9 on 2025-12-10 11:43

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_clientopinion_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioindexpage',
            name='images',
            field=wagtail.fields.StreamField([('images', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'image', 'required': True}), 1: ('wagtail.blocks.StructBlock', [[('image', 0)]], {}), 2: ('wagtail.blocks.ListBlock', (1,), {})}),
        ),
    ]
