# Generated by Django 5.2.9 on 2025-12-10 13:13

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_portfolioindexpage_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliopage',
            name='body',
        ),
        migrations.AlterField(
            model_name='portfolioindexpage',
            name='images',
            field=wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'image', 'required': True})}),
        ),
        migrations.AlterField(
            model_name='portfoliopage',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom du project'),
        ),
    ]
